// This code conforms with the UFC specification version 2018.1.0
// and was automatically generated by FFC version 2019.1.0.post0.
//
// This code was generated with the following parameters:
//

//  add_tabulate_tensor_timing:     False
//  convert_exceptions_to_warnings: False
//  cpp_optimize:                   True
//  cpp_optimize_flags:             '-O2'
//  epsilon:                        1e-14
//  error_control:                  False
//  external_include_dirs:          ['/usr/local/include', '/usr/local/slepc-32/includ
//                                  e', '/usr/local/petsc-32/include', '/usr/include/m
//                                  pich', '/usr/include/hdf5/mpich', '/usr/include/ei
//                                  gen3', '/usr/local/lib/python3.6/dist-packages/ffc
//                                  /backends/ufc']
//  external_includes:              ''
//  external_libraries:             ''
//  external_library_dirs:          ''
//  form_postfix:                   False
//  format:                         'ufc'
//  generate_dummy_tabulate_tensor: False
//  max_signature_length:           0
//  no-evaluate_basis_derivatives:  True
//  optimize:                       True
//  precision:                      None
//  quadrature_degree:              6
//  quadrature_rule:                None
//  representation:                 'auto'
//  split:                          False

#include "ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4.h"

// Based on https://gcc.gnu.org/wiki/Visibility
#if defined _WIN32 || defined __CYGWIN__
    #ifdef __GNUC__
        #define DLL_EXPORT __attribute__ ((dllexport))
    #else
        #define DLL_EXPORT __declspec(dllexport)
    #endif
#else
    #define DLL_EXPORT __attribute__ ((visibility ("default")))
#endif

ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_cell_integral_main_otherwise::ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_cell_integral_main_otherwise() : ufc::cell_integral()
{

}

ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_cell_integral_main_otherwise::~ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_cell_integral_main_otherwise()
{

}

const std::vector<bool> & ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_cell_integral_main_otherwise::enabled_coefficients() const
{
static const std::vector<bool> enabled({true, true, true, true, true, true, true});
return enabled;
}

void ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_cell_integral_main_otherwise::tabulate_tensor(double * A,
                                    const double * const * w,
                                    const double * coordinate_dofs,
                                    int cell_orientation) const
{
    // This function was generated using 'uflacs' representation
    // with the following integrals metadata:
    // 
    // num_cells:         None
    // optimize:          True
    // precision:         16
    // quadrature_degree: 6
    // quadrature_rule:   'default'
    // representation:    'uflacs'
    // 
    // and the following integral 0 metadata:
    // 
    // estimated_polynomial_degree: 3
    // optimize:                    True
    // precision:                   16
    // quadrature_degree:           6
    // quadrature_rule:             'default'
    // representation:              'uflacs'
    // Quadrature rules
    alignas(32) static const double weights12[12] = { 0.0254224531851035, 0.0254224531851035, 0.0254224531851035, 0.0583931378631895, 0.0583931378631895, 0.0583931378631895, 0.041425537809187, 0.041425537809187, 0.041425537809187, 0.041425537809187, 0.041425537809187, 0.041425537809187 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [entities][points][dofs]
    // PI* dimensions: [entities][dofs][dofs] or [entities][dofs]
    // PM* dimensions: [entities][dofs][dofs]
    alignas(32) static const double FE3_C0_D01_Q12[1][1][2] = { { { -1.0, 1.0 } } };
    alignas(32) static const double FE3_C0_Q12[1][12][3] =
        { { { 0.06308901449150206, 0.873821971016996, 0.063089014491502 },
            { 0.06308901449150206, 0.06308901449150206, 0.8738219710169959 },
            { 0.873821971016996, 0.06308901449150206, 0.063089014491502 },
            { 0.249286745170911, 0.501426509658179, 0.24928674517091 },
            { 0.249286745170911, 0.24928674517091, 0.501426509658179 },
            { 0.50142650965818, 0.24928674517091, 0.24928674517091 },
            { 0.05314504984481599, 0.6365024991213991, 0.310352451033785 },
            { 0.310352451033785, 0.636502499121399, 0.05314504984481599 },
            { 0.05314504984481605, 0.3103524510337851, 0.636502499121399 },
            { 0.636502499121399, 0.310352451033785, 0.05314504984481599 },
            { 0.3103524510337851, 0.05314504984481605, 0.636502499121399 },
            { 0.6365024991213991, 0.05314504984481599, 0.310352451033785 } } };
    // Unstructured piecewise computations
    const double J_c0 = coordinate_dofs[0] * FE3_C0_D01_Q12[0][0][0] + coordinate_dofs[2] * FE3_C0_D01_Q12[0][0][1];
    const double J_c3 = coordinate_dofs[1] * FE3_C0_D01_Q12[0][0][0] + coordinate_dofs[5] * FE3_C0_D01_Q12[0][0][1];
    const double J_c1 = coordinate_dofs[0] * FE3_C0_D01_Q12[0][0][0] + coordinate_dofs[4] * FE3_C0_D01_Q12[0][0][1];
    const double J_c2 = coordinate_dofs[1] * FE3_C0_D01_Q12[0][0][0] + coordinate_dofs[3] * FE3_C0_D01_Q12[0][0][1];
    alignas(32) double sp[4];
    sp[0] = J_c0 * J_c3;
    sp[1] = J_c1 * J_c2;
    sp[2] = sp[0] + -1 * sp[1];
    sp[3] = std::abs(sp[2]);
    alignas(32) double BF0[3] = {};
    for (int iq = 0; iq < 12; ++iq)
    {
        // Quadrature loop body setup (num_points=12)
        // Unstructured varying computations for num_points=12
        double w0 = 0.0;
        for (int ic = 0; ic < 3; ++ic)
            w0 += w[0][ic] * FE3_C0_Q12[0][iq][ic];
        alignas(32) double sv12[8];
        sv12[0] = w0 + w[2][0];
        sv12[1] = w[1][0] / sv12[0];
        sv12[2] = -1 * w[3][0] + sv12[1];
        sv12[3] = (sv12[2] > w[4][0] ? sv12[2] : w[4][0]);
        sv12[4] = sv12[3] * w[5][0];
        sv12[5] = sv12[3] + w[6][0];
        sv12[6] = sv12[4] / sv12[5];
        sv12[7] = sv12[6] * sp[3];
        const double fw0 = sv12[7] * weights12[iq];
        for (int i = 0; i < 3; ++i)
            BF0[i] += fw0 * FE3_C0_Q12[0][iq][i];
    }
    std::fill(A, A + 3, 0.0);
    for (int i = 0; i < 3; ++i)
        A[i] += BF0[i];
}

extern "C" DLL_EXPORT ufc::cell_integral * create_ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_cell_integral_main_otherwise()
{
  return new ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_cell_integral_main_otherwise();
}


ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main() : ufc::form()
{
    // Do nothing
}

ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::~ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main()
{
    // Do nothing
}

const char * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::signature() const
{
    return "f7a7597e96d7b3bd125381a4940d45adb364a383b7db798dd93d7b2cab38153c61069a197bdc9d19634f690adb6d54f9dcfb9b83e6a0ed54cb2fac14c8934281";
}

std::size_t ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::rank() const
{
    return 1;
}

std::size_t ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::num_coefficients() const
{
    return 7;
}

std::size_t ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::original_coefficient_position(std::size_t i) const
{
    if (i >= 7)
    {
        throw std::runtime_error("Invalid original coefficient index.");
    }
    static const std::vector<std::size_t> position = {0, 1, 2, 3, 4, 5, 6};
    return position[i];
}

ufc::finite_element * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_coordinate_finite_element() const
{
    return create_ffc_element_7dab2aa9daa90928cff28e50a6f6e0c438396aee_finite_element_main();
}

ufc::dofmap * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_coordinate_dofmap() const
{
    return create_ffc_element_7dab2aa9daa90928cff28e50a6f6e0c438396aee_dofmap_main();
}

ufc::coordinate_mapping * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_coordinate_mapping() const
{
    return create_ffc_coordinate_mapping_46e04ce83042cae36646f6564b7b0146332e9b0b_coordinate_mapping_main();
}

ufc::finite_element * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_finite_element(std::size_t i) const
{
    switch (i)
    {
    case 0:
        return create_ffc_element_895c79d22561b12f05dc45ad1c57b019ad8e31cf_finite_element_main();
    case 1:
        return create_ffc_element_895c79d22561b12f05dc45ad1c57b019ad8e31cf_finite_element_main();
    case 2:
        return create_ffc_element_dfa0b22379dafecc52a8a14150cd36dccf7e8103_finite_element_main();
    case 3:
        return create_ffc_element_dfa0b22379dafecc52a8a14150cd36dccf7e8103_finite_element_main();
    case 4:
        return create_ffc_element_dfa0b22379dafecc52a8a14150cd36dccf7e8103_finite_element_main();
    case 5:
        return create_ffc_element_dfa0b22379dafecc52a8a14150cd36dccf7e8103_finite_element_main();
    case 6:
        return create_ffc_element_dfa0b22379dafecc52a8a14150cd36dccf7e8103_finite_element_main();
    case 7:
        return create_ffc_element_dfa0b22379dafecc52a8a14150cd36dccf7e8103_finite_element_main();
    default:
        return nullptr;
    }
}

ufc::dofmap * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_dofmap(std::size_t i) const
{
    switch (i)
    {
    case 0:
        return create_ffc_element_895c79d22561b12f05dc45ad1c57b019ad8e31cf_dofmap_main();
    case 1:
        return create_ffc_element_895c79d22561b12f05dc45ad1c57b019ad8e31cf_dofmap_main();
    case 2:
        return create_ffc_element_dfa0b22379dafecc52a8a14150cd36dccf7e8103_dofmap_main();
    case 3:
        return create_ffc_element_dfa0b22379dafecc52a8a14150cd36dccf7e8103_dofmap_main();
    case 4:
        return create_ffc_element_dfa0b22379dafecc52a8a14150cd36dccf7e8103_dofmap_main();
    case 5:
        return create_ffc_element_dfa0b22379dafecc52a8a14150cd36dccf7e8103_dofmap_main();
    case 6:
        return create_ffc_element_dfa0b22379dafecc52a8a14150cd36dccf7e8103_dofmap_main();
    case 7:
        return create_ffc_element_dfa0b22379dafecc52a8a14150cd36dccf7e8103_dofmap_main();
    default:
        return nullptr;
    }
}

std::size_t ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::max_cell_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::max_exterior_facet_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::max_interior_facet_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::max_vertex_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::max_custom_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::max_cutcell_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::max_interface_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::max_overlap_subdomain_id() const
{
    return 0;
}

bool ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::has_cell_integrals() const
{
    return true;
}

bool ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::has_exterior_facet_integrals() const
{
    return false;
}

bool ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::has_interior_facet_integrals() const
{
    return false;
}

bool ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::has_vertex_integrals() const
{
    return false;
}

bool ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::has_custom_integrals() const
{
    return false;
}

bool ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::has_cutcell_integrals() const
{
    return false;
}

bool ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::has_interface_integrals() const
{
    return false;
}

bool ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::has_overlap_integrals() const
{
    return false;
}

ufc::cell_integral * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_cell_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::exterior_facet_integral * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_exterior_facet_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::interior_facet_integral * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_interior_facet_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::vertex_integral * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_vertex_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::custom_integral * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_custom_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::cutcell_integral * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_cutcell_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::interface_integral * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_interface_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::overlap_integral * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_overlap_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::cell_integral * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_default_cell_integral() const
{
    return create_ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_cell_integral_main_otherwise();
}

ufc::exterior_facet_integral * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_default_exterior_facet_integral() const
{
    return nullptr;
}

ufc::interior_facet_integral * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_default_interior_facet_integral() const
{
    return nullptr;
}

ufc::vertex_integral * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_default_vertex_integral() const
{
    return nullptr;
}

ufc::custom_integral * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_default_custom_integral() const
{
    return nullptr;
}

ufc::cutcell_integral * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_default_cutcell_integral() const
{
    return nullptr;
}

ufc::interface_integral * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_default_interface_integral() const
{
    return nullptr;
}

ufc::overlap_integral * ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main::create_default_overlap_integral() const
{
    return nullptr;
}

extern "C" DLL_EXPORT ufc::form * create_ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main()
{
  return new ffc_form_9b3a30f74875282fd650a319b97c83b3284f92d4_form_main();
}

