import os


# Mesh and output paths. The BackStep meshes are generated by
# Meshes/BackStep/generate_wall_resolved_meshes.py with y+ ~= 1 first-layer
# spacing. Lam-Bremhorst is a low-Re k-epsilon model, so it should use the same
# wall-resolved mesh requirement as the SA backstep case.
MESH_DIRECTORY = "Meshes/BackStep/Fine/mesh.xdmf"
FACET_DIRECTORY = "Meshes/BackStep/Fine/facet.xdmf"


def infer_mesh_label_from_path(path):
    path_parts = os.path.normpath(path).split(os.sep)
    for mesh_label in ("Coarse", "Medium", "Fine"):
        if mesh_label in path_parts:
            return mesh_label
    return path_parts[-2] if len(path_parts) >= 2 else "UnknownMesh"


MESH_LABEL = infer_mesh_label_from_path(MESH_DIRECTORY)
RESULTS_ROOT = "Results/BackStep_K-Epsilon/{}_Steady".format(MESH_LABEL)


# Boundary markers from the BackStep mesh.
boundary_markers = {
    "INFLOW": [4],
    "OUTFLOW": [2],
    "WALLS": [1, 3],
    "SYMMETRY": [5],
}


# Geometry inferred from the supplied mesh/facet markers.
INLET_X = -32.5
OUTLET_X = 12.5
STEP_X = 0.0
UPSTREAM_LOWER_WALL_Y = 0.0
DOWNSTREAM_LOWER_WALL_Y = -0.25
TOP_WALL_Y = 2.0
STEP_HEIGHT = UPSTREAM_LOWER_WALL_Y - DOWNSTREAM_LOWER_WALL_Y
INLET_HEIGHT = TOP_WALL_Y - UPSTREAM_LOWER_WALL_Y
OUTLET_HEIGHT = TOP_WALL_Y - DOWNSTREAM_LOWER_WALL_Y


# Physical quantities.
INLET_VELOCITY = (25.0, 0.0)
U_REFERENCE = INLET_VELOCITY[0]
KINEMATIC_VISCOSITY = 0.000181818
BODY_FORCE = (0.0, 0.0)
REYNOLDS_NUMBER_STEP = U_REFERENCE * STEP_HEIGHT / KINEMATIC_VISCOSITY
REYNOLDS_NUMBER_INLET_HEIGHT = U_REFERENCE * INLET_HEIGHT / KINEMATIC_VISCOSITY
SKIN_FRICTION_COEFFICIENT = 0.079 * (REYNOLDS_NUMBER_STEP ** -0.25)
FRICTION_VELOCITY = U_REFERENCE * (SKIN_FRICTION_COEFFICIENT / 2.0) ** 0.5
TARGET_FIRST_LAYER_HEIGHT = KINEMATIC_VISCOSITY / FRICTION_VELOCITY

# Reynolds number:
#   Re_h = U_ref * h / nu = 25.0 * 0.25 / 0.000181818 = 3.44e4
#   Re_H = U_ref * H_in / nu = 25.0 * 2.0 / 0.000181818 = 2.75e5
# Use Re_h when comparing against standard backward-facing-step references.
# Wall resolution:
#   Cf = 0.079 Re_h^(-0.25), u_tau = U_ref sqrt(Cf/2)
#   y_first(y+=1) = nu/u_tau = 1.35e-4 m.


# Legacy Lam-Bremhorst inlet turbulence values.
K_INLET = 1.73
E_INLET = 1.46


# Initial conditions.
initial_conditions = {
    "U": (0.0, 0.0),
    "P": 0.0,
    "K": K_INLET,
    "E": E_INLET,
}


# Boundary conditions.
boundary_conditions = {
    "INFLOW": {
        "U": INLET_VELOCITY,
        "P": None,
        "K": K_INLET,
        "E": E_INLET,
    },
    "OUTFLOW": {
        "U": None,
        "P": 0.0,
        "K": None,
        "E": None,
    },
    "WALLS": {
        "U": (0.0, 0.0),
        "P": None,
        "K": 0.0,
        "E": None,
    },
    "SYMMETRY": {
        "U": 0.0,
        "P": None,
        "K": None,
        "E": None,
    },
}


physical_prm = {
    "VISCOSITY": KINEMATIC_VISCOSITY,
    "FORCE": BODY_FORCE,
}


# Simulation parameters. This is a steady mixed Picard solve.
simulation_prm = {
    "QUADRATURE_DEGREE": 2,
    "MAX_ITERATIONS": 3000,
    "TOLERANCE": 1e-6,
    "PICARD_RELAXATION": 0.1,
}


mesh_files = {
    "MESH_DIRECTORY": MESH_DIRECTORY,
    "FACET_DIRECTORY": FACET_DIRECTORY,
}


saving_directory = {
    "PVD_FILES": "{}/PVD files/".format(RESULTS_ROOT),
    "H5_FILES": "{}/H5 files/".format(RESULTS_ROOT),
    "RESIDUALS": "{}/Residual files/".format(RESULTS_ROOT),
}


post_processing = {
    "PLOT": False,
    "SAVE": True,
}
