name: ttofrozen-ubend-dilgen
services:
  run:
    container_name: turbulentto-frozen-ubend-dilgen
    image: fenics/stable:py3
    platform: linux/amd64
    volumes:
      - ../../:/home/fenics/shared
    environment:
      HDF5_USE_FILE_LOCKING: "FALSE"
    entrypoint: ["/bin/bash", "-lc"]
    command: "cd /home/fenics/shared/FluidTO && exec python3 TurbulentTO_Frozen.py --config Configs_Frozen/Config_UBendDilgen_Frozen.py"
