name: ttofrozen-doublepipe-borrvall
services:
  run:
    container_name: turbulentto-frozen-doublepipe-borrvall
    image: quay.io/fenicsproject/stable:current
    working_dir: /home/fenics/shared
    volumes:
      - ../../:/home/fenics/shared
    environment:
      HDF5_USE_FILE_LOCKING: "FALSE"
    entrypoint:
      - python3
      - FluidTO/TurbulentTO_Frozen.py
      - --config
      - FluidTO/Configs_Frozen/Config_DoublePipeBorrvall_Frozen.py
