name: ttofrozen-ubend-dilgen
services:
  run:
    container_name: turbulentto-frozen-ubend-dilgen
    build:
      context: .
      dockerfile: Dockerfile
    image: turbulentto-frozen-fenics:local
    working_dir: /home/fenics/shared
    volumes:
      - ../../:/home/fenics/shared
    environment:
      HDF5_USE_FILE_LOCKING: "FALSE"
    command:
      - FluidTO/TurbulentTO_Frozen.py
      - --config
      - FluidTO/Configs_Frozen/Config_UBendDilgen_Frozen.py
