name: ttofrozen-pipebend-dilgen
services:
  run:
    container_name: turbulentto-frozen-pipebend-dilgen
    image: fenics/stable:py3
    platform: linux/amd64
    working_dir: /home/fenics/shared/FluidTO
    volumes:
      - ../../:/home/fenics/shared
    environment:
      HDF5_USE_FILE_LOCKING: "FALSE"
    command:
      - python3
      - TurbulentTO_Frozen.py
      - --config
      - Configs_Frozen/Config_PipeBendDilgen_Frozen.py
