// This code conforms with the UFC specification version 2018.1.0
// and was automatically generated by FFC version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//

//  add_tabulate_tensor_timing:     False
//  convert_exceptions_to_warnings: False
//  cpp_optimize:                   True
//  cpp_optimize_flags:             '-O2'
//  epsilon:                        1e-14
//  error_control:                  False
//  external_include_dirs:          ''
//  external_includes:              ''
//  external_libraries:             ''
//  external_library_dirs:          ''
//  form_postfix:                   False
//  format:                         'ufc'
//  generate_dummy_tabulate_tensor: False
//  max_signature_length:           0
//  no-evaluate_basis_derivatives:  True
//  optimize:                       True
//  precision:                      None
//  quadrature_degree:              6
//  quadrature_rule:                None
//  representation:                 'auto'
//  split:                          False

#include "ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e.h"

// Based on https://gcc.gnu.org/wiki/Visibility
#if defined _WIN32 || defined __CYGWIN__
    #ifdef __GNUC__
        #define DLL_EXPORT __attribute__ ((dllexport))
    #else
        #define DLL_EXPORT __declspec(dllexport)
    #endif
#else
    #define DLL_EXPORT __attribute__ ((visibility ("default")))
#endif

ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_cell_integral_main_otherwise::ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_cell_integral_main_otherwise() : ufc::cell_integral()
{

}

ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_cell_integral_main_otherwise::~ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_cell_integral_main_otherwise()
{

}

const std::vector<bool> & ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_cell_integral_main_otherwise::enabled_coefficients() const
{
static const std::vector<bool> enabled({true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true});
return enabled;
}

void ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_cell_integral_main_otherwise::tabulate_tensor(double * A,
                                    const double * const * w,
                                    const double * coordinate_dofs,
                                    int cell_orientation,
                                    std::size_t local_facet) const
{
    // This function was generated using 'uflacs' representation
    // with the following integrals metadata:
    // 
    // num_cells:         None
    // optimize:          True
    // precision:         16
    // quadrature_degree: 6
    // quadrature_rule:   'default'
    // representation:    'uflacs'
    // 
    // and the following integral 0 metadata:
    // 
    // estimated_polynomial_degree: 5
    // optimize:                    True
    // precision:                   16
    // quadrature_degree:           6
    // quadrature_rule:             'default'
    // representation:              'uflacs'
    // Quadrature rules
    alignas(32) static const double weights12[12] = { 0.0254224531851035, 0.0254224531851035, 0.0254224531851035, 0.0583931378631895, 0.0583931378631895, 0.0583931378631895, 0.041425537809187, 0.041425537809187, 0.041425537809187, 0.041425537809187, 0.041425537809187, 0.041425537809187 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [entities][points][dofs]
    // PI* dimensions: [entities][dofs][dofs] or [entities][dofs]
    // PM* dimensions: [entities][dofs][dofs]
    alignas(32) static const double FE3_C0_D01_Q12[1][1][2] = { { { -1.0, 1.0 } } };
    alignas(32) static const double FE3_C0_Q12[1][12][3] =
        { { { 0.06308901449150196, 0.873821971016996, 0.06308901449150202 },
            { 0.06308901449150202, 0.06308901449150207, 0.8738219710169959 },
            { 0.873821971016996, 0.06308901449150202, 0.06308901449150202 },
            { 0.249286745170911, 0.501426509658179, 0.24928674517091 },
            { 0.249286745170911, 0.24928674517091, 0.501426509658179 },
            { 0.50142650965818, 0.24928674517091, 0.24928674517091 },
            { 0.05314504984481595, 0.636502499121399, 0.310352451033785 },
            { 0.3103524510337849, 0.6365024991213991, 0.05314504984481597 },
            { 0.05314504984481599, 0.3103524510337851, 0.636502499121399 },
            { 0.636502499121399, 0.310352451033785, 0.05314504984481597 },
            { 0.310352451033785, 0.05314504984481604, 0.636502499121399 },
            { 0.636502499121399, 0.053145049844816, 0.310352451033785 } } };
    // Unstructured piecewise computations
    const double J_m7_c0 = coordinate_dofs[0] * FE3_C0_D01_Q12[0][0][0] + coordinate_dofs[2] * FE3_C0_D01_Q12[0][0][1];
    const double J_m7_c3 = coordinate_dofs[1] * FE3_C0_D01_Q12[0][0][0] + coordinate_dofs[5] * FE3_C0_D01_Q12[0][0][1];
    const double J_m7_c1 = coordinate_dofs[0] * FE3_C0_D01_Q12[0][0][0] + coordinate_dofs[4] * FE3_C0_D01_Q12[0][0][1];
    const double J_m7_c2 = coordinate_dofs[1] * FE3_C0_D01_Q12[0][0][0] + coordinate_dofs[3] * FE3_C0_D01_Q12[0][0][1];
    const double w14_d1_m7 = w[14][0] * FE3_C0_D01_Q12[0][0][0] + w[14][2] * FE3_C0_D01_Q12[0][0][1];
    double w14_d0_m7 = 0.0;
    for (int ic = 0; ic < 2; ++ic)
        w14_d0_m7 += w[14][ic] * FE3_C0_D01_Q12[0][0][ic];
    alignas(32) double sp[47];
    sp[0] = J_m7_c0 * J_m7_c3;
    sp[1] = J_m7_c1 * J_m7_c2;
    sp[2] = sp[0] + -1 * sp[1];
    sp[3] = J_m7_c0 / sp[2];
    sp[4] = -1 * J_m7_c1 / sp[2];
    sp[5] = w14_d1_m7 * sp[3];
    sp[6] = w14_d0_m7 * sp[4];
    sp[7] = sp[5] + sp[6];
    sp[8] = sp[7] * sp[3];
    sp[9] = sp[7] * sp[4];
    sp[10] = J_m7_c3 / sp[2];
    sp[11] = -1 * J_m7_c2 / sp[2];
    sp[12] = w14_d0_m7 * sp[10];
    sp[13] = w14_d1_m7 * sp[11];
    sp[14] = sp[12] + sp[13];
    sp[15] = sp[14] * sp[11];
    sp[16] = sp[14] * sp[10];
    sp[17] = sp[8] + sp[15];
    sp[18] = sp[16] + sp[9];
    sp[19] = w[10][0] * w[18][0];
    sp[20] = sp[19] + w[17][0];
    sp[21] = -1 * w[2][0] + w[3][0];
    sp[22] = -1 * w[5][0] + w[1][0];
    sp[23] = sp[22] * w[0][0];
    sp[24] = std::tanh(sp[23]);
    sp[25] = w[0][0] * w[4][0];
    sp[26] = std::tanh(sp[25]);
    sp[27] = sp[24] + sp[26];
    sp[28] = -1 * w[8][0] + w[7][0];
    sp[29] = sp[28] * w[0][0];
    sp[30] = std::tanh(sp[29]);
    sp[31] = w[0][0] * w[6][0];
    sp[32] = std::tanh(sp[31]);
    sp[33] = sp[30] + sp[32];
    sp[34] = sp[27] / sp[33];
    sp[35] = sp[21] * sp[34];
    sp[36] = sp[35] + w[2][0];
    sp[37] = -1 * sp[36] + w[13][0];
    sp[38] = (sp[37] > w[15][0] ? sp[37] : w[15][0]);
    sp[39] = sp[38] / w[13][0];
    sp[40] = std::pow(sp[39], w[12][0]);
    sp[41] = sp[7] * sp[7];
    sp[42] = sp[14] * sp[14];
    sp[43] = sp[41] + sp[42];
    sp[44] = -1 * w[10][0] + w[16][0];
    sp[45] = sp[43] * sp[44];
    sp[46] = std::abs(sp[2]);
    alignas(32) double BF0[2] = {};
    alignas(32) double BF1[3] = {};
    alignas(32) double BF2[2] = {};
    for (int iq = 0; iq < 12; ++iq)
    {
        // Quadrature loop body setup (num_points=12)
        // Unstructured varying computations for num_points=12
        double w14_m7 = 0.0;
        for (int ic = 0; ic < 3; ++ic)
            w14_m7 += w[14][ic] * FE3_C0_Q12[0][iq][ic];
        alignas(32) double sv12[12];
        sv12[0] = w[10][0] * w14_m7;
        sv12[1] = sp[17] * sv12[0];
        sv12[2] = sp[18] * sv12[0];
        sv12[3] = sp[20] * std::pow(w14_m7, 4);
        sv12[4] = -1 * w[9][0] + w14_m7;
        sv12[5] = sv12[4] * w[11][0];
        sv12[6] = sv12[5] * sp[40];
        sv12[7] = sv12[3] + sv12[6];
        sv12[8] = -1 * sv12[7] + sp[45];
        sv12[9] = -1 * sv12[1] * sp[46];
        sv12[10] = -1 * sv12[2] * sp[46];
        sv12[11] = sv12[8] * sp[46];
        const double fw0 = sv12[10] * weights12[iq];
        for (int i = 0; i < 2; ++i)
            BF0[i] += fw0 * FE3_C0_D01_Q12[0][0][i];
        const double fw1 = sv12[11] * weights12[iq];
        for (int i = 0; i < 3; ++i)
            BF1[i] += fw1 * FE3_C0_Q12[0][iq][i];
        const double fw2 = sv12[9] * weights12[iq];
        for (int i = 0; i < 2; ++i)
            BF2[i] += fw2 * FE3_C0_D01_Q12[0][0][i];
    }
    std::fill(A, A + 3, 0.0);
    static const int DM0[2] = { 0, 2 };
    for (int i = 0; i < 2; ++i)
        A[i] += BF0[i];
    for (int i = 0; i < 3; ++i)
        A[i] += BF1[i];
    for (int i = 0; i < 2; ++i)
        A[DM0[i]] += BF2[i];
}

extern "C" DLL_EXPORT ufc::cell_integral * create_ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_cell_integral_main_otherwise()
{
  return new ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_cell_integral_main_otherwise();
}


ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main() : ufc::form()
{
    // Do nothing
}

ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::~ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main()
{
    // Do nothing
}

const char * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::signature() const
{
    return "d2183bf98167ae2feb50be283c2e83603a190f8de43f94b56d49f12e0575360d696797dc1496467debf377d2f709da6c22f99a503481151c9c08974b4ba3a8aa";
}

std::size_t ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::rank() const
{
    return 1;
}

std::size_t ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::num_coefficients() const
{
    return 19;
}

std::size_t ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::original_coefficient_position(std::size_t i) const
{
    if (i >= 19)
    {
        throw std::runtime_error("Invalid original coefficient index.");
    }
    static const std::vector<std::size_t> position = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};
    return position[i];
}

ufc::finite_element * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_coordinate_finite_element() const
{
    return create_ffc_element_ddf506a5f7febc58fa7fb0880edd1f74ff7ce47b_finite_element_main();
}

ufc::dofmap * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_coordinate_dofmap() const
{
    return create_ffc_element_ddf506a5f7febc58fa7fb0880edd1f74ff7ce47b_dofmap_main();
}

ufc::coordinate_mapping * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_coordinate_mapping() const
{
    return create_ffc_coordinate_mapping_3694c766e8181855e34495542117b20eecc1906f_coordinate_mapping_main();
}

ufc::finite_element * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_finite_element(std::size_t i) const
{
    switch (i)
    {
    case 0:
        return create_ffc_element_a8770767d73726634e7c96a84e585b14f518e6ee_finite_element_main();
    case 1:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_finite_element_main();
    case 2:
        return create_ffc_element_4f1fddca753be4199402328ef4bd743d22899776_finite_element_main();
    case 3:
        return create_ffc_element_4f1fddca753be4199402328ef4bd743d22899776_finite_element_main();
    case 4:
        return create_ffc_element_4f1fddca753be4199402328ef4bd743d22899776_finite_element_main();
    case 5:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_finite_element_main();
    case 6:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_finite_element_main();
    case 7:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_finite_element_main();
    case 8:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_finite_element_main();
    case 9:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_finite_element_main();
    case 10:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_finite_element_main();
    case 11:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_finite_element_main();
    case 12:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_finite_element_main();
    case 13:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_finite_element_main();
    case 14:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_finite_element_main();
    case 15:
        return create_ffc_element_a8770767d73726634e7c96a84e585b14f518e6ee_finite_element_main();
    case 16:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_finite_element_main();
    case 17:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_finite_element_main();
    case 18:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_finite_element_main();
    case 19:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_finite_element_main();
    default:
        return nullptr;
    }
}

ufc::dofmap * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_dofmap(std::size_t i) const
{
    switch (i)
    {
    case 0:
        return create_ffc_element_a8770767d73726634e7c96a84e585b14f518e6ee_dofmap_main();
    case 1:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_dofmap_main();
    case 2:
        return create_ffc_element_4f1fddca753be4199402328ef4bd743d22899776_dofmap_main();
    case 3:
        return create_ffc_element_4f1fddca753be4199402328ef4bd743d22899776_dofmap_main();
    case 4:
        return create_ffc_element_4f1fddca753be4199402328ef4bd743d22899776_dofmap_main();
    case 5:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_dofmap_main();
    case 6:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_dofmap_main();
    case 7:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_dofmap_main();
    case 8:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_dofmap_main();
    case 9:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_dofmap_main();
    case 10:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_dofmap_main();
    case 11:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_dofmap_main();
    case 12:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_dofmap_main();
    case 13:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_dofmap_main();
    case 14:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_dofmap_main();
    case 15:
        return create_ffc_element_a8770767d73726634e7c96a84e585b14f518e6ee_dofmap_main();
    case 16:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_dofmap_main();
    case 17:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_dofmap_main();
    case 18:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_dofmap_main();
    case 19:
        return create_ffc_element_616b865979a837336fb5810dc0f3641affaf4e01_dofmap_main();
    default:
        return nullptr;
    }
}

std::size_t ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::max_cell_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::max_exterior_facet_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::max_interior_facet_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::max_vertex_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::max_custom_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::max_cutcell_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::max_interface_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::max_overlap_subdomain_id() const
{
    return 0;
}

bool ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::has_cell_integrals() const
{
    return true;
}

bool ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::has_exterior_facet_integrals() const
{
    return false;
}

bool ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::has_interior_facet_integrals() const
{
    return false;
}

bool ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::has_vertex_integrals() const
{
    return false;
}

bool ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::has_custom_integrals() const
{
    return false;
}

bool ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::has_cutcell_integrals() const
{
    return false;
}

bool ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::has_interface_integrals() const
{
    return false;
}

bool ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::has_overlap_integrals() const
{
    return false;
}

ufc::cell_integral * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_cell_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::exterior_facet_integral * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_exterior_facet_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::interior_facet_integral * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_interior_facet_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::vertex_integral * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_vertex_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::custom_integral * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_custom_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::cutcell_integral * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_cutcell_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::interface_integral * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_interface_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::overlap_integral * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_overlap_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::cell_integral * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_default_cell_integral() const
{
    return create_ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_cell_integral_main_otherwise();
}

ufc::exterior_facet_integral * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_default_exterior_facet_integral() const
{
    return nullptr;
}

ufc::interior_facet_integral * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_default_interior_facet_integral() const
{
    return nullptr;
}

ufc::vertex_integral * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_default_vertex_integral() const
{
    return nullptr;
}

ufc::custom_integral * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_default_custom_integral() const
{
    return nullptr;
}

ufc::cutcell_integral * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_default_cutcell_integral() const
{
    return nullptr;
}

ufc::interface_integral * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_default_interface_integral() const
{
    return nullptr;
}

ufc::overlap_integral * ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main::create_default_overlap_integral() const
{
    return nullptr;
}

extern "C" DLL_EXPORT ufc::form * create_ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main()
{
  return new ffc_form_a99396b67685d2aada4569d9e20ef73046b13a4e_form_main();
}

