import os as _os
import sys as _sys

_CONFIG_DIR = _os.path.dirname(_os.path.abspath(__file__))
_REPO_ROOT = _os.path.dirname(_CONFIG_DIR)
if _REPO_ROOT not in _sys.path:
    _sys.path.insert(0, _REPO_ROOT)

from Configs_Frozen.Config_PipeBendAlexandersen_Frozen import *  # noqa: F401,F403


# ===================================================================
# Alexandersen pipe-bend pressure objective, old J_p variant.
#
# This keeps the pressure-objective setup from commit
# 8fedc94ac985eae21a8c550fa0adff8dd393271c, but writes to a separate
# results folder and defaults to a non-continuation 500-iteration run.
# It does not modify the current PipeBendAlexandersen J_p config.
# ===================================================================

RESUME_OPTIMIZATION = False

VOL_FRAC = 0.25
OBJECTIVE_TYPE = "average_inlet_pressure"
INITIAL_DENSITY_VALUE = VOL_FRAC
INITIAL_DENSITY_MATCH_FILTERED_VOLUME = True

# Old J_p run: weak Brinkman impedance was important for reproducing
# the Alexandersen-like bend topology.
ALPHA_SOLID = 100.0

# Old frozen-SA settings from 8fedc94.
SA_SUPG_STABILIZATION = False
SA_SUPG_TAU_SCALE = 1.0
SA_PSEUDO_TIME_STABILIZATION = False
SA_PSEUDO_DT = 1.0e-4
SA_PSEUDO_TIME_STEPS = 3

SA_NU_TILDE_PENALTY_ALPHA = 1.0e3
SA_NU_TILDE_PENALTY_ALPHA_SCHEDULE = [1.0e3]
SA_NU_TILDE_PENALTY_N = 4.0
SA_NU_TILDE_PENALTY_INTERPOLATION = "power"

SA_WALL_DISTANCE_MODE = "reciprocal_penalized"
SA_WALL_SIGMA = 0.01
SA_WALL_G0 = 20.0
SA_WALL_PENALTY_ALPHA = 1.0e3
SA_WALL_PENALTY_ALPHA_SCHEDULE = [1.0e3]
SA_WALL_PENALTY_N = 4.0
SA_WALL_PENALTY_INTERPOLATION = "power"
SA_WALL_G_FLOOR = 1.0e-8

PICARD_STEPS = 3
TURBULENCE_RELAXATION = 0.20

LINEAR_SOLVER = "mumps"

FORWARD_FLOW_SOLVER = "snes"
FORWARD_PICARD_FLOW_SOLVER = "ipcs"
FORWARD_SNES_WARM_START_WITH_IPCS = True
FORWARD_SNES_IPCS_WARM_START_MODE = "final"
FORWARD_SNES_STRICT_FINAL_SOLVE = False

FORWARD_SNES_METHOD = "newtonls"
FORWARD_SNES_LINE_SEARCH = "bt"
FORWARD_SNES_LINEAR_SOLVER = "mumps"
FORWARD_SNES_RTOL = 1.0e-6
FORWARD_SNES_ATOL = 1.0e-8
FORWARD_SNES_MAX_ITERS = 220
FORWARD_SNES_ADAPTIVE_CONVECTION = True
FORWARD_SNES_MIN_CONVECTION_STEP = 0.03
FORWARD_SNES_MAX_ADAPTIVE_CONVECTION_STEPS = 16

# Neutralize newer base-config safeguards so this file stays close to 8fedc94.
FORWARD_SNES_STOP_AT_ACCEPT_NORM = False
FORWARD_RETRY_BACKTRACK_DESIGN = False
FORWARD_RETRY_BACKTRACK_FACTORS = [0.5, 0.25, 0.10, 0.05]

FORWARD_IPCS_DT = 2.5e-6
FORWARD_IPCS_MAX_ITERS = 300
FORWARD_IPCS_VELOCITY_RTOL = 1.0e-4
FORWARD_IPCS_PRESSURE_RTOL = 2.0e-3
FORWARD_IPCS_VEL_RELAXATION = 0.07
FORWARD_IPCS_P_RELAXATION = 0.02
FORWARD_IPCS_VEL_SOLVER = "bicgstab"
FORWARD_IPCS_VEL_PRECONDITIONER = "ilu"
FORWARD_IPCS_P_SOLVER = "bicgstab"
FORWARD_IPCS_P_PRECONDITIONER = "ilu"
FORWARD_IPCS_LOG_EVERY = 50
FORWARD_IPCS_MAX_RESTARTS = 2
FORWARD_IPCS_DT_REDUCTION_FACTOR = 0.5
FORWARD_IPCS_RELAXATION_REDUCTION_FACTOR = 0.7
FORWARD_IPCS_ACCEPT_BEST_SCORE = 1.0
FORWARD_IPCS_PICARD_VELOCITY_RTOL = FORWARD_IPCS_VELOCITY_RTOL
FORWARD_IPCS_PICARD_PRESSURE_RTOL = FORWARD_IPCS_PRESSURE_RTOL
FORWARD_IPCS_PICARD_ACCEPT_BEST_SCORE = FORWARD_IPCS_ACCEPT_BEST_SCORE

# Choose one:
#   "single_stage_500"   TA fallback: hold q and beta fixed for 500 MMA iterations.
#   "smooth_continuation" gentler version of the old schedule.
#   "legacy_8fedc94"     exact continuation from the oscillating run.
CONTINUATION_VARIANT = "single_stage_500"

PAPER_Q_ALPHA_LEGACY = [150.0, 75.0, 30.0, 15.0]
Q_PENAL_LEGACY = [1.0 / q_alpha for q_alpha in PAPER_Q_ALPHA_LEGACY]
BETA_PROJ_LEGACY = [4.0, 6.0, 9.0, 13.0]
MOVE_LIMIT_LEGACY = [0.05, 0.04, 0.03, 0.02]
MAX_INNER_ITERATIONS_LEGACY = [25, 25, 25, 25]

if CONTINUATION_VARIANT == "single_stage_500":
    PAPER_Q_ALPHA_SCHEDULE = [150.0]
    Q_PENAL_SCHEDULE = [1.0 / PAPER_Q_ALPHA_SCHEDULE[0]]
    BETA_PROJ_SCHEDULE = [4.0]
    MOVE_LIMIT_SCHEDULE = [0.010]
    MAX_INNER_ITERATIONS_SCHEDULE = [500]
    OBJECTIVE_CONVERGENCE_TOL = 0.0
    OBJECTIVE_STREAK_TO_STOP = 500
elif CONTINUATION_VARIANT == "smooth_continuation":
    PAPER_Q_ALPHA_SCHEDULE = [150.0, 120.0, 100.0, 75.0, 50.0, 30.0, 15.0]
    Q_PENAL_SCHEDULE = [1.0 / q_alpha for q_alpha in PAPER_Q_ALPHA_SCHEDULE]
    BETA_PROJ_SCHEDULE = [2.0, 2.5, 3.0, 4.0, 5.5, 7.0, 9.0]
    MOVE_LIMIT_SCHEDULE = [0.015, 0.012, 0.010, 0.008, 0.006, 0.004, 0.003]
    MAX_INNER_ITERATIONS_SCHEDULE = [60, 60, 70, 80, 100, 120, 160]
    OBJECTIVE_CONVERGENCE_TOL = 1.0e-5
    OBJECTIVE_STREAK_TO_STOP = 12
elif CONTINUATION_VARIANT == "legacy_8fedc94":
    PAPER_Q_ALPHA_SCHEDULE = PAPER_Q_ALPHA_LEGACY
    Q_PENAL_SCHEDULE = Q_PENAL_LEGACY
    BETA_PROJ_SCHEDULE = BETA_PROJ_LEGACY
    MOVE_LIMIT_SCHEDULE = MOVE_LIMIT_LEGACY
    MAX_INNER_ITERATIONS_SCHEDULE = MAX_INNER_ITERATIONS_LEGACY
    OBJECTIVE_CONVERGENCE_TOL = 1.0e-5
    OBJECTIVE_STREAK_TO_STOP = 5
else:
    raise ValueError(
        "CONTINUATION_VARIANT must be 'single_stage_500', "
        "'smooth_continuation', or 'legacy_8fedc94'."
    )

MAX_INNER_ITERATIONS = MAX_INNER_ITERATIONS_SCHEDULE[0]
BETA_PROJ_VALUE = BETA_PROJ_SCHEDULE[0]

SAVE_SA_CLIPPING_DIAGNOSTICS = False
SAVE_DF0DX_VECTOR = False
SAVE_IPCS_RESIDUAL_PLOTS = False
SAVE_IPCS_RESIDUAL_SVGS = False

RESULTS_ROOT_NAME = "Results_Frozen/Results_PipeBendAlexandersen_Frozen_Jp_Old"
